Document how to use Jaeger
quarkusio/quarkus-super-heroes pull request #122
Opened 2022-07-31 07:01 UTC by agoncal

Fix #116

2022-08-01 17:27 UTC, edeandrea requested changes
See in-line comments.

Also, we should add a link at the top of the README which links directly to the Jaeger section.

2022-08-01 17:27 UTC, edeandrea commented on README.md
> +Open the Jaeger UI by going to `http://localhost:16686`.
This won't necessarily be true unless they are running everything locally. We mention above (in both the docker compose section & the deploying to kubernetes section) that Jaeger is deployed and how to access it.

Maybe we just say "Open the Jaeger UI based on how you are running the system, either through [Docker Compose](#running-locally-via-docker-compose) or by [deploying the monitoring stack to kubernetes](#monitoring).

2022-08-01 17:27 UTC, edeandrea commented on README.md
> +You can see that each trace contains 12 total spans:
Its actually 14 total spans (I know where you got that number from - I added JDBC tracing last week and the place where you got that was written before I made that change :) )

2022-08-01 17:27 UTC, edeandrea commented on README.md
> +six spans in the `rest-fights` application, four spans in the `rest-heroes` application, and two spans in the `rest-villains` application.
six spans in `rest-fights`, four spans in `rest-heroes`, and four spans in `rest-villains` - for the same reason as my previous comment.

2022-08-03 07:43 UTC, agoncal commented
Done

2022-08-03 13:46 UTC, edeandrea approved these changes

2022-08-03 13:46 UTC, merged